# Generated by Django 5.2.5 on 2025-08-14 03:34

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="biografia",
            field=martor.models.MartorField(
                blank=True, null=True, verbose_name="Biografía"
            ),
        ),
    ]
